namespace CleanDDTest.Models
{
    public class EmpRef
    {
        public string Pernr { get; set; } = null!;
        public DateTime EnddaVal { get; set; }
        public DateTime BegdaVal { get; set; }
        public DateTime Aedtm { get; set; }
        public string? Stat2 { get; set; }
        public string? Text1 { get; set; }
        public string? Massn10 { get; set; }
        public string? Massg10 { get; set; }
        public string? Mgtxt10 { get; set; }
        public DateTime? Begda10 { get; set; }
        public string? Massn34 { get; set; }
        public string? Massg34 { get; set; }
        public string? Mgtxt34 { get; set; }
        public DateTime? Begda34 { get; set; }
        public string? Massn35 { get; set; }
        public string? Massg35 { get; set; }
        public string? Mgtxt35 { get; set; }
        public DateTime? Begda35 { get; set; }
        public DateTime? Begda36 { get; set; }
        public DateTime? Begda0001 { get; set; }
        public DateTime? Endda0001 { get; set; }
        public string? Werks { get; set; }
        public string? Persg { get; set; }
        public string? Persk { get; set; }
        public string? Btrtl { get; set; }
        public string? Kostl { get; set; }
        public string? Plans { get; set; }
        public string? Ename { get; set; }
        public string? Zzverstatus { get; set; }
        public string? Filler2 { get; set; }
        public string? Empct1 { get; set; }
        public decimal? Prozt { get; set; }
        public string? Plstx { get; set; }
        public string? Nachn { get; set; }
        public string? Vorna { get; set; }
        public string? Namzu { get; set; }
        public string? Rufnm { get; set; }
        public string? Midnm { get; set; }
        public string? Anred { get; set; }
        public string? Gesch { get; set; }
        public DateTime? Gbdat { get; set; }
        public string? Famst { get; set; }
        public string? Perid { get; set; }
        public string? Ftext { get; set; }
        public string? Atext { get; set; }
        public string? Subty1 { get; set; }
        public string? Name21 { get; set; }
        public string? Stras1 { get; set; }
        public string? Ort011 { get; set; }
        public string? Ort021 { get; set; }
        public string? State1 { get; set; }
        public string? Pstlz1 { get; set; }
        public string? Land11 { get; set; }
        public string? Telnr1 { get; set; }
        public string? Locat1 { get; set; }
        public string? County1 { get; set; }
        public string? Phone1 { get; set; }
        public string? Name23 { get; set; }
        public string? Stras3 { get; set; }
        public string? Ort013 { get; set; }
        public string? Ort023 { get; set; }
        public string? State3 { get; set; }
        public string? Pstlz3 { get; set; }
        public string? Land13 { get; set; }
        public string? Telnr3 { get; set; }
        public string? Locat3 { get; set; }
        public string? County3 { get; set; }
        public string? Phone3 { get; set; }
        public string? Buildcd { get; set; }
        public string? Roomnr { get; set; }
        public string? Build { get; set; }
        public string? Room { get; set; }
        public DateTime? Dat01 { get; set; }
        public DateTime? Dat02 { get; set; }
        public DateTime? Dat03 { get; set; }
        public DateTime? Dat04 { get; set; }
        public DateTime? Dat05 { get; set; }
        public DateTime? Dat06 { get; set; }
        public DateTime? Dat07 { get; set; }
        public DateTime? Dat08 { get; set; }
        public DateTime? Dat09 { get; set; }
        public DateTime? Dat10 { get; set; }
        public DateTime? Dat11 { get; set; }
        public DateTime? Dat12 { get; set; }
        public DateTime? Actiondate { get; set; }
        public string? Racky { get; set; }
        public string? Usrid { get; set; }
        public string? Tnid { get; set; }
        public string? Bplan { get; set; }
        public string? Quota30 { get; set; }
        public string? Quota40 { get; set; }
        public string? Quota60 { get; set; }
        public string? Quota70 { get; set; }
        public string? Quota80 { get; set; }
        public decimal? Anzhl30 { get; set; }
        public decimal? Anzhl40 { get; set; }
        public decimal? Anzhl60 { get; set; }
        public decimal? Anzhl70 { get; set; }
        public decimal? Anzhl80 { get; set; }
        public string? Abkrs { get; set; }
        public string? Geschtxt { get; set; }
        public string? Gbdep { get; set; }
        public string? Gblnd { get; set; }
        public decimal? ZzUtflexper { get; set; }
        public string? ZzUtflexper1 { get; set; }
        public string? Resis { get; set; }
        public string? Natio { get; set; }
        public string? Visat { get; set; }
        public DateTime? Ablad { get; set; }
        public string? Status { get; set; }
        public DateTime? Revdate { get; set; }
        public DateTime? Tendate { get; set; }
        public string? Location { get; set; }
        public string? College { get; set; }
        public string? Dept { get; set; }
        public string? Slart { get; set; }
        public string? Slabs { get; set; }
        public string? Counc1 { get; set; }
        public string? Counc2 { get; set; }
        public string? Nbrex { get; set; }
        public string? ZzdiscAuth { get; set; }
        public string? Stell { get; set; }
        public string? Jobtext { get; set; }
        public string? Exmpt1 { get; set; }
        public string? Exmpt { get; set; }
        public string? Eeo { get; set; }
        public string? Begda { get; set; }
        public string? Endda { get; set; }
        public string? Short { get; set; }
        public string? ZzphoneOv { get; set; }
        public string? Cntry { get; set; }
        public string? City { get; set; }
        public string? Stret { get; set; }
        public string? Zipcd { get; set; }
        public string? State { get; set; }
        public string? CellPh { get; set; }
        public string? Bplanfm { get; set; }
        public string? Bplanfd { get; set; }
        public string? Bplanfb { get; set; }
        public string? Bpland { get; set; }
        public string? Depcvd { get; set; }
        public string? Bplanh { get; set; }
        public string? Depcvh { get; set; }
        public string? Bplanal { get; set; }
        public string? Bcovral { get; set; }
        public string? Bplanfi { get; set; }
        public string? Bcovrfi1 { get; set; }
        public string? Bcovrfi2 { get; set; }
        public string? Bcovrfi3 { get; set; }
        public string? Bcovrfi4 { get; set; }
        public string? Bplanbl { get; set; }
        public string? Bcovrbl { get; set; }
        public string? Bplanltd { get; set; }
        public string? Bcovrltd { get; set; }
        public string? Bplanoal { get; set; }
        public string? Bcovroal { get; set; }
        public string? Bplanv { get; set; }
        public string? Bcovrotl1 { get; set; }
        public string? Bcovrotl2 { get; set; }
        public string? Bcovrotl3 { get; set; }
        public string? Depcvv { get; set; }
        public string? Bcovroule { get; set; }
        public string? Bcovrouls { get; set; }
        public string? Bcovroulb { get; set; }
        public DateTime? Zi9date { get; set; }
        public string? Lastpaydate { get; set; }
        public string? Aauplgart { get; set; }
        public string? Booklgart { get; set; }
        public string? Creditlgart { get; set; }
        public string? Tsealgart { get; set; }
        public string? Bplanrt { get; set; }
        public string? Z403b { get; set; }
        public string? Z403l { get; set; }
        public string? Z401k { get; set; }
        public string? Z401n { get; set; }
        public string? Z457 { get; set; }
        public string? Tspn { get; set; }
        public string? Tsp { get; set; }
        public string? Aapct { get; set; }
        public string? Titlecodedate { get; set; }
        public string? Bstat { get; set; }
        public string? Ansvh { get; set; }
        public string? Funkt1 { get; set; }
        public string? Fstext1 { get; set; }
        public string? Zzcorpct1 { get; set; }
        public string? Funkt2 { get; set; }
        public string? Fstext2 { get; set; }
        public string? Zzcorpct2 { get; set; }
        public string? Funkt3 { get; set; }
        public string? Fstext3 { get; set; }
        public string? Zzcorpct3 { get; set; }
        public string? Funkt4 { get; set; }
        public string? Fstext4 { get; set; }
        public string? Zzcorpct4 { get; set; }
        public string? Funkt5 { get; set; }
        public string? Fstext5 { get; set; }
        public string? Zzcorpct5 { get; set; }
        public string? Funkt6 { get; set; }
        public string? Fstext6 { get; set; }
        public string? Zzcorpct6 { get; set; }
        public string? Zlsch { get; set; }
        public string? Orgeh { get; set; }
        public string? Zzunvcon { get; set; }
        public string? Temppaycnt { get; set; }
        public string? Schkz { get; set; }
        public string? Wostd1 { get; set; }
        public string? Txexm01 { get; set; }
        public string? Txexm02 { get; set; }
        public string? Txexm03 { get; set; }
        public string? Txexm04 { get; set; }
        public string? Txexmstf { get; set; }
        public string? Vetst { get; set; }
        public string? Visas { get; set; }
        public string? Trfar { get; set; }
        public string? Trfgb { get; set; }
        public string? Trfgr { get; set; }
        public string? Rank { get; set; }
        public DateTime? Rankdate { get; set; }
        public string? Discipline { get; set; }
        public string? Ansal { get; set; }
        public string? Agencey { get; set; }
        public string? Effhour { get; set; }
        public string? Grossytd { get; set; }
        public string? Eicst { get; set; }
        public string? Exind { get; set; }
        public string? Txtty { get; set; }
        public string? Txsta { get; set; }
        public string? Konst { get; set; }
        public string? Retirementcont { get; set; }
        public string? Retmkwert { get; set; }
        public string? Ficakwert { get; set; }
        public string? Oasdikwert { get; set; }
        public string? Ficamkwert { get; set; }
        public string? Tsppct { get; set; }
        public string? Z401kmkwert { get; set; }
        public string? Ercstl { get; set; }
        public string? Ercsth { get; set; }
        public string? Wcomprkwert { get; set; }
        public string? Unemplkwert { get; set; }
        public string? Unemplmkwert { get; set; }
        public string? Com01 { get; set; }
        public string? Levl1 { get; set; }
        public string? Num01 { get; set; }
        public DateTime? Createdate { get; set; }
        public DateTime? Entry { get; set; }
        public string? Census { get; set; }
        public string? McStext { get; set; }
        public string? Hpool { get; set; }
        public string? Ptext { get; set; }
        public string? Orgtx { get; set; }
        public string? Ltext { get; set; }
        public string? Stltx { get; set; }
        public string? Jobltx { get; set; }
        public string? Appplans { get; set; }
        public string? Poscnt { get; set; }
        public DateTime? Expid { get; set; }
        public string? Itxex1 { get; set; }
        public string? Itxex3 { get; set; }
        public string? Prozt1 { get; set; }
        public string? Prozt2 { get; set; }
        public string? Ipt01 { get; set; }
        public string? Ipt02 { get; set; }
        public string? Ipt03 { get; set; }
        public string? Mailstop { get; set; }
        public string? Edlevel { get; set; }
        public decimal? Uhours { get; set; }
        public decimal? Ghours { get; set; }
        public string? Z2ndpersg { get; set; }
        public string? Z2ndpersk { get; set; }
        public string? Z2ndpersa { get; set; }
        public string? Z2ndbtrtl { get; set; }
        public string? Z2ndshort { get; set; }
        public string? Z2ndstext { get; set; }
        public string? Stat1 { get; set; }
        public string? Rstus { get; set; }
        public string? Astat { get; set; }
        public DateTime? Arrivlda { get; set; }
        public DateTime? Departda { get; set; }
        public DateTime? Sptdt { get; set; }
        public string? Examt { get; set; }
        public string? KostlTrav { get; set; }
        public string? NatioT { get; set; }
        public string? DegYear { get; set; }
        public string? PswPolExpInd { get; set; }
        public string? PortalAutArray { get; set; }
        public string? Ethen { get; set; }
        public string? Rac01 { get; set; }
        public string? Rac02 { get; set; }
        public string? Rac03 { get; set; }
        public string? Rac04 { get; set; }
        public string? Rac05 { get; set; }
        public string? Rac06 { get; set; }
        public string? Rac07 { get; set; }
        public string? Rac08 { get; set; }
        public string? Rac09 { get; set; }
        public string? Rac10 { get; set; }
        public string? Vets1 { get; set; }
        public string? Vets2 { get; set; }
        public string? Vets3 { get; set; }
        public string? Vets4 { get; set; }
        public string? Vets5 { get; set; }
        public string? Vets6 { get; set; }
        public string? Vets7 { get; set; }
        public string? Vets8 { get; set; }
        public string? Vets9 { get; set; }
        public string? Vets10 { get; set; }
        public DateTime? Dcrdt { get; set; }
        public string? Fictr { get; set; }
        public string? ChgFlg { get; set; }
        public string? Z2ndptext { get; set; }
        public string? Z2ndeeo { get; set; }
        public string? Name24 { get; set; }
        public string? Stras4 { get; set; }
        public string? Ort014 { get; set; }
        public string? Ort024 { get; set; }
        public string? Pstlz4 { get; set; }
        public string? Land14 { get; set; }
        public string? Telnr4 { get; set; }
        public string? Locat4 { get; set; }
        public string? State4 { get; set; }
        public string? County4 { get; set; }
        public string? Entcd { get; set; }
        public string? Colcd { get; set; }
        public string? Dptcd { get; set; }
        public string? CipCode { get; set; }
        public string? Fincode { get; set; }
        public string? Stext { get; set; }
        public string? TalFlg { get; set; }
        public string? CandNo { get; set; }
        public string? TalRoles { get; set; }
        public string? Fax { get; set; }
        public string? TalFlgUser { get; set; }
        public string? Filler3 { get; set; }
        public string? BwAutArray { get; set; }
        public string? EsmRoles { get; set; }
        public string? EsmFlgUser { get; set; }
        public string? EsmFlg { get; set; }
        public string? Bplan401h { get; set; }
        public string? Bengr { get; set; }
        public string? Retirementcoee { get; set; }
        public string? Z401kRetireEr { get; set; }
        public string? Eepct01 { get; set; }
        public string? Eepct02 { get; set; }
        public string? Eepct03 { get; set; }
        public string? CfFeeWaiver { get; set; }
        public string? EviRoles { get; set; }
        public string? EviFlgUser { get; set; }
        public string? Ytdgrosspay { get; set; }
        public DateTime? Bgdat { get; set; }
        public string? WtFlgUser { get; set; }
        public string? LmsFlgUser { get; set; }
        public string? EsmAppr { get; set; }
        public string? SubCipCode { get; set; }
        public string? Ergru { get; set; }
        public string? Ptzuo { get; set; }
        public string? Kzpmf { get; set; }
        public string? Spebe { get; set; }
        public string? ManEmpId { get; set; }
        public string? Concur305 { get; set; }
        public string? Concur320 { get; set; }
        public string? Concur910 { get; set; }
        public string? Zznocshadvnc { get; set; }
        public string? Zzconcurfnd { get; set; }
        public DateTime? AppEndda { get; set; }
        public DateTime? Dat13 { get; set; }
        public string? EdisonId { get; set; }
        public string? Lifnr { get; set; }

    }
}
